language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls coverage
script:
  - coverage run --source mocurly setup.py test
after_success:
  - coveralls
